// Generated from factory/policies/cedar/*.cedar. Run `pnpm factory:policies:sync` after editing canonical policy files.
export const FACTORY_POLICY_TEXT: Readonly<Record<string, string>> = {
  "factory-delivery-driver-merges-low-risk-change": "@id(\"factory-delivery-driver-merges-low-risk-change\")\npermit (\n  principal == Factory::ServicePrincipal::\"factory-delivery-driver\",\n  action == Factory::Action::\"merge_change\",\n  resource is Factory::Change\n)\nwhen {\n  principal.hasTag(\"role\") &&\n  principal.getTag(\"role\") == \"merge-coordinator\" &&\n  context.lane == \"merge\" &&\n  context.riskClass == \"low\" &&\n  context.branch == resource.defaultBranch &&\n  context has evidence &&\n  context.evidence.complete == true &&\n  context.evidence.source == \"factory.merge-policy\" &&\n  context has reviewedSha &&\n  context.reviewedSha == resource.candidateSha &&\n  context.input.pullRequest == resource.changeId &&\n  context.input.targetBranch == context.branch\n};\n",
  "factory-forbid-default-branch-publication": "@id(\"factory-forbid-default-branch-publication\")\nforbid (\n  principal,\n  action == Factory::Action::\"publish_change\",\n  resource is Factory::Change\n)\nwhen {\n  context.branch == resource.defaultBranch ||\n  context.input.branch == resource.defaultBranch\n};\n",
  "factory-forbid-elevated-auto-merge": "@id(\"factory-forbid-elevated-auto-merge\")\nforbid (\n  principal,\n  action == Factory::Action::\"merge_change\",\n  resource is Factory::Change\n)\nwhen { context.riskClass != \"low\" };\n",
  "factory-forbid-missing-evidence": "@id(\"factory-forbid-missing-evidence\")\nforbid (\n  principal,\n  action in [\n    Factory::Action::\"record_verification\",\n    Factory::Action::\"record_review\",\n    Factory::Action::\"publish_change\",\n    Factory::Action::\"merge_change\"\n  ],\n  resource\n)\nwhen { !(context has evidence) };\n",
  "factory-forbid-stale-change-state": "@id(\"factory-forbid-stale-change-state\")\nforbid (\n  principal,\n  action in [\n    Factory::Action::\"record_verification\",\n    Factory::Action::\"record_review\",\n    Factory::Action::\"publish_change\",\n    Factory::Action::\"merge_change\"\n  ],\n  resource is Factory::Change\n)\nwhen {\n  context.candidateSha != resource.candidateSha ||\n  context.baseSha != resource.baseSha ||\n  context.verifiedSha != resource.candidateSha ||\n  context.expectedRevision != resource.expectedRevision\n};\n",
  "factory-forbid-unadmitted-start": "@id(\"factory-forbid-unadmitted-start\")\nforbid (\n  principal,\n  action == Factory::Action::\"start_task\",\n  resource\n)\nunless {\n  context has admission &&\n  context.admission.kind == \"work_order\"\n};\n",
  "factory-forbid-unbound-service-mutation": "@id(\"factory-forbid-unbound-service-mutation\")\nforbid (\n  principal is Factory::ServicePrincipal,\n  action in [\n    Factory::Action::\"record_verification\",\n    Factory::Action::\"record_review\",\n    Factory::Action::\"publish_change\",\n    Factory::Action::\"merge_change\"\n  ],\n  resource\n)\nwhen {\n  !(\n    principal.hasTag(\"role\") &&\n    [\"worker\", \"reviewer\", \"merge-coordinator\"].contains(principal.getTag(\"role\"))\n  )\n};\n",
  "factory-forbid-untrusted-evidence": "@id(\"factory-forbid-untrusted-evidence\")\nforbid (\n  principal,\n  action in [\n    Factory::Action::\"record_verification\",\n    Factory::Action::\"record_review\",\n    Factory::Action::\"publish_change\",\n    Factory::Action::\"merge_change\"\n  ],\n  resource\n)\nwhen {\n  context has evidence &&\n  (\n    context.evidence.complete != true ||\n    context.evidence.candidateSha != context.candidateSha ||\n    ![\n      \"factory.prepare_work\",\n      \"factory.prepare_review\",\n      \"factory.verify_work\",\n      \"factory.verify_review\",\n      \"factory.review_gate\",\n      \"factory.merge-policy\"\n    ].contains(context.evidence.source)\n  )\n};\n",
  "factory-reviewer-records-review": "@id(\"factory-reviewer-records-review\")\npermit (\n  principal,\n  action == Factory::Action::\"record_review\",\n  resource is Factory::Change\n)\nwhen {\n  principal.hasTag(\"role\") &&\n  principal.getTag(\"role\") == \"reviewer\" &&\n  context.lane == \"reviewer\" &&\n  context has evidence &&\n  context.evidence.complete == true &&\n  context.evidence.source == \"factory.review_gate\" &&\n  context has reviewedSha &&\n  context.input.reviewedSha == context.reviewedSha &&\n  context.input.reviewedSha == resource.candidateSha\n};\n",
  "factory-reviewer-records-verification": "@id(\"factory-reviewer-records-verification\")\npermit (\n  principal,\n  action == Factory::Action::\"record_verification\",\n  resource is Factory::Change\n)\nwhen {\n  principal.hasTag(\"role\") &&\n  principal.getTag(\"role\") == \"reviewer\" &&\n  context.lane == \"reviewer\" &&\n  context has evidence &&\n  context.evidence.complete == true &&\n  context.evidence.source == \"factory.verify_review\" &&\n  context.input.outcome == \"passed\" &&\n  context.input.evidenceId == context.evidence.id\n};\n",
  "factory-reviewer-runs-checks": "@id(\"factory-reviewer-runs-checks\")\npermit (\n  principal,\n  action == Factory::Action::\"run_check\",\n  resource is Factory::Repository\n)\nwhen {\n  principal.hasTag(\"role\") &&\n  principal.getTag(\"role\") == \"reviewer\" &&\n  context.lane == \"reviewer\" &&\n  context has evidence &&\n  context.evidence.complete == true &&\n  context.evidence.source == \"factory.prepare_review\"\n};\n",
  "factory-worker-publishes-verified-change": "@id(\"factory-worker-publishes-verified-change\")\npermit (\n  principal,\n  action == Factory::Action::\"publish_change\",\n  resource is Factory::Change\n)\nwhen {\n  principal.hasTag(\"role\") &&\n  principal.getTag(\"role\") == \"worker\" &&\n  context.lane == \"worker\" &&\n  context.branch like \"factory/*\" &&\n  context.branch != resource.defaultBranch &&\n  context has evidence &&\n  context.evidence.complete == true &&\n  context.evidence.source == \"factory.verify_work\" &&\n  context.verifiedSha == resource.candidateSha &&\n  context.input.candidateSha == resource.candidateSha &&\n  context.input.baseSha == resource.baseSha &&\n  context.input.branch == context.branch &&\n  context.input.draft == true\n};\n",
  "factory-worker-records-verification": "@id(\"factory-worker-records-verification\")\npermit (\n  principal,\n  action == Factory::Action::\"record_verification\",\n  resource is Factory::Change\n)\nwhen {\n  principal.hasTag(\"role\") &&\n  principal.getTag(\"role\") == \"worker\" &&\n  context.lane == \"worker\" &&\n  context has evidence &&\n  context.evidence.complete == true &&\n  context.evidence.source == \"factory.verify_work\" &&\n  context.input.outcome == \"passed\" &&\n  context.input.evidenceId == context.evidence.id\n};\n",
  "factory-worker-runs-checks": "@id(\"factory-worker-runs-checks\")\npermit (\n  principal,\n  action == Factory::Action::\"run_check\",\n  resource is Factory::Repository\n)\nwhen {\n  principal.hasTag(\"role\") &&\n  principal.getTag(\"role\") == \"worker\" &&\n  context.lane == \"worker\" &&\n  context has evidence &&\n  context.evidence.complete == true &&\n  context.evidence.source == \"factory.prepare_work\"\n};\n",
  "factory-workflow-starts-admitted-work-order": "@id(\"factory-workflow-starts-admitted-work-order\")\npermit (\n  principal == Factory::ServicePrincipal::\"factory-workflow\",\n  action == Factory::Action::\"start_task\",\n  resource is Factory::Repository\n)\nwhen {\n  principal.hasTag(\"role\") &&\n  principal.getTag(\"role\") == \"workflow\" &&\n  context.lane == \"audit\" &&\n  context has admission &&\n  context.admission.kind == \"work_order\" &&\n  context.input.deliveryId == context.admission.id\n};\n",
};

export const FACTORY_POLICY_REVISION = "sha256:88d8568277bb1c3d74155d321cf1f7f8ced8d7e83cf44a030874cb4129616835";
